name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Jekyll and dependencies
        run: |
          gem install bundler jekyll
          bundle install || true

      - name: Build the Jekyll site
        run: |
          JEKYLL_ENV=production bundle exec jekyll build -d _site
          ls -l _site

      - name: Deploy to GitHub Pages (docs branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: docs
          force_orphan: true
          cname: www.aw3consulting.com
